In [1]:
import pandas as pd 
import numpy as np 
import warnings

warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('../data/indian_tech_jobs_2026_final.csv')

In [3]:
df.shape

(23201, 32)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23201 entries, 0 to 23200
Data columns (total 32 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   job_title                                 23201 non-null  object
 1   company_name                              23201 non-null  object
 2   company_rating                            23201 non-null  float64
 3   location                                  23201 non-null  object
 4   experience_min_yrs                        23201 non-null  float64
 5   experience_max_yrs                        23201 non-null  float64
 6   salary_min_lpa                            23201 non-null  float64
 7   salary_max_lpa                            23201 non-null  float64
 8   salary_midpoint_lpa                       23201 non-null  float64
 9   salary_disclosed                          23201 non-null  int64
 10  skills_required                           23201 non-null  object
 11  skills_count                              23201 non-null  int64
 12  salary_tier                               23201 non-null  int64
 13  experience_tier                           23201 non-null  int64
 14  is_senior                                 23201 non-null  int64
 15  primary_city                              23201 non-null  object
 16  days_since_posted                         23201 non-null  float64
 17  is_fresher_friendly                       23201 non-null  int64
 18  salary_negotiable                         23201 non-null  int64
 19  role_category_Data Analyst                23201 non-null  int64
 20  role_category_Data Engineer               23201 non-null  int64
 21  role_category_Data Scientist              23201 non-null  int64
 22  role_category_Machine Learning Engineer   23201 non-null  int64
 23  role_category_Python Developer            23201 non-null  int64
 24  work_mode_On-Site                         23201 non-null  int64
 25  work_mode_Remote                          23201 non-null  int64
 26  company_size_bucket_Mid (100-999)         23201 non-null  int64
 27  company_size_bucket_Small/Startup (<100)  23201 non-null  int64
 28  skill_domain_Business Intelligence        23201 non-null  int64
 29  skill_domain_Cloud & DevOps               23201 non-null  int64
 30  skill_domain_Data Engineering             23201 non-null  int64
 31  skill_domain_Data Science                 23201 non-null  int64
dtypes: float64(7), int64(20), object(5)
memory usage: 5.7+ MB

In [5]:
df.head(5)

,job_title,company_name,company_rating,location,experience_min_yrs,experience_max_yrs,salary_min_lpa,salary_max_lpa,salary_midpoint_lpa,salary_disclosed,...,role_category_Machine Learning Engineer,role_category_Python Developer,work_mode_On-Site,work_mode_Remote,company_size_bucket_Mid (100-999),company_size_bucket_Small/Startup (<100),skill_domain_Business Intelligence,skill_domain_Cloud & DevOps,skill_domain_Data Engineering,skill_domain_Data Science
0,Data Scientist,Cisco,4.1,Bengaluru,7.0,10.0,0.0,0.0,0.0,0,...,0,0,1,0,0,0,1,0,0,0
1,Data Scientist,Caterpillar Inc,4.1,Bengaluru,4.0,8.0,0.0,0.0,0.0,0,...,0,0,1,0,0,1,0,0,0,0
2,Analytics Data Scientist,Foreign It Consulting Mnc,3.6,"Hyderabad, Chennai, Bengaluru",4.0,9.0,0.0,0.0,0.0,0,...,0,0,1,0,0,0,1,0,0,0
3,Data Scientist,Fortune 500 It Services Company,3.6,"Mumbai, Bengaluru",0.0,0.0,0.0,0.0,0.0,0,...,0,0,1,0,0,1,0,0,0,1
4,Sr. Artificial Intelligence Engineer,Fortune 500 Product-Based Mnc,3.6,"Pune, Bengaluru",5.0,10.0,0.0,0.0,0.0,0,...,0,0,1,0,0,1,0,0,0,1

In [6]:
df.describe()

,company_rating,experience_min_yrs,experience_max_yrs,salary_min_lpa,salary_max_lpa,salary_midpoint_lpa,salary_disclosed,skills_count,salary_tier,experience_tier,...,role_category_Machine Learning Engineer,role_category_Python Developer,work_mode_On-Site,work_mode_Remote,company_size_bucket_Mid (100-999),company_size_bucket_Small/Startup (<100),skill_domain_Business Intelligence,skill_domain_Cloud & DevOps,skill_domain_Data Engineering,skill_domain_Data Science
count,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,...,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000
mean,3.586449,4.135080,7.829059,1.383952,2.271790,1.827872,0.119305,7.604198,4.726520,2.447351,...,0.172579,0.068359,0.806043,0.092798,0.002802,0.813241,0.479462,0.101030,0.068747,0.066678
std,0.514250,2.933976,3.946834,4.841570,7.469383,6.109373,0.324154,1.456530,0.894952,1.288208,...,0.377891,0.252367,0.395404,0.290155,0.052857,0.389726,0.499589,0.301375,0.253029,0.249469
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.400000,2.000000,5.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,1.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,3.600000,4.000000,8.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,3.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,3.800000,6.000000,10.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,3.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
max,5.000000,25.000000,31.000000,85.000000,90.000000,87.500000,1.000000,8.000000,5.000000,4.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
df.columns

Index(['job_title', 'company_name', 'company_rating', 'location',
       'experience_min_yrs', 'experience_max_yrs', 'salary_min_lpa',
       'salary_max_lpa', 'salary_midpoint_lpa', 'salary_disclosed',
       'skills_required', 'skills_count', 'salary_tier', 'experience_tier',
       'is_senior', 'primary_city', 'days_since_posted', 'is_fresher_friendly',
       'salary_negotiable', 'role_category_Data Analyst',
       'role_category_Data Engineer', 'role_category_Data Scientist',
       'role_category_Machine Learning Engineer',
       'role_category_Python Developer', 'work_mode_On-Site',
       'work_mode_Remote', 'company_size_bucket_Mid (100-999)',
       'company_size_bucket_Small/Startup (<100)',
       'skill_domain_Business Intelligence', 'skill_domain_Cloud & DevOps',
       'skill_domain_Data Engineering', 'skill_domain_Data Science'],
      dtype='object')

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [18]:
X = df[
    [
        'company_rating',
        'experience_min_yrs',
        'experience_max_yrs',
        'salary_min_lpa',
        'salary_max_lpa',
        'salary_midpoint_lpa',
        'salary_disclosed',
        'skills_count',
        'salary_tier',
        'experience_tier',
        'is_senior',
        'days_since_posted',
        'is_fresher_friendly',
        'salary_negotiable',
        'work_mode_On-Site',
        'work_mode_Remote',
        'company_size_bucket_Mid (100-999)',
        'company_size_bucket_Small/Startup (<100)',
        'skill_domain_Business Intelligence',
        'skill_domain_Cloud & DevOps',
        'skill_domain_Data Engineering',
        'skill_domain_Data Science'
    ]
] 


role_columns = [
    'role_category_Data Analyst',
    'role_category_Data Engineer',
    'role_category_Data Scientist',
    'role_category_Machine Learning Engineer',
    'role_category_Python Developer'
]

y = df[role_columns].idxmax(axis=1)
y = y.str.replace('role_category_', '')

In [20]:
from sklearn.tree import DecisionTreeClassifier

In [21]:
model_DT = DecisionTreeClassifier()
model_DT.fit(X_train,y_train)

DecisionTreeClassifier()

In [22]:
y_pred_DT = model_DT.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


accuracy_score(y_test,y_pred_DT)

0.6543848308554191

In [27]:
confusion_matrix(y_test,y_pred_DT)

array([[1569,   37,  173,   32,    8],
       [  55,  167,  150,    8,   15],
       [ 309,  137,  583,  179,   86],
       [  44,    4,  190,  560,   15],
       [  13,   21,  112,   16,  158]])

In [28]:
print(classification_report(y_test,y_pred_DT))

                           precision    recall  f1-score   support

             Data Analyst       0.79      0.86      0.82      1819
            Data Engineer       0.46      0.42      0.44       395
           Data Scientist       0.48      0.45      0.47      1294
Machine Learning Engineer       0.70      0.69      0.70       813
         Python Developer       0.56      0.49      0.52       320

                 accuracy                           0.65      4641
                macro avg       0.60      0.58      0.59      4641
             weighted avg       0.64      0.65      0.65      4641