In [11]:
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
from sklearn.cluster import KMeans
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')

In [47]:
dataset = sns.load_dataset('tips')

dataset.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [48]:
df.shape

(891, 16)

In [49]:
df.head(5)

,alone_False,alone_True,class_First,class_Second,class_Third,embarked_C,embarked_Q,embarked_S,embarked_Unknown,sex_female,sex_male,survived_0,survived_1,who_child,who_man,who_woman
0,True,False,False,False,True,False,False,True,False,False,True,True,False,False,True,False
1,True,False,True,False,False,True,False,False,False,True,False,False,True,False,False,True
2,False,True,False,False,True,False,False,True,False,True,False,False,True,False,False,True
3,True,False,True,False,False,False,False,True,False,True,False,False,True,False,False,True
4,False,True,False,False,True,False,False,True,False,False,True,True,False,False,True,False

In [50]:
df.describe()

,alone_False,alone_True,class_First,class_Second,class_Third,embarked_C,embarked_Q,embarked_S,embarked_Unknown,sex_female,sex_male,survived_0,survived_1,who_child,who_man,who_woman
count,891,891,891,891,891,891,891,891,891,891,891,891,891,891,891,891
unique,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
top,False,True,False,False,True,False,False,True,False,False,True,True,False,False,True,False
freq,537,537,675,707,491,723,814,644,889,577,577,549,549,808,537,620

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   alone_False       891 non-null    bool
 1   alone_True        891 non-null    bool
 2   class_First       891 non-null    bool
 3   class_Second      891 non-null    bool
 4   class_Third       891 non-null    bool
 5   embarked_C        891 non-null    bool
 6   embarked_Q        891 non-null    bool
 7   embarked_S        891 non-null    bool
 8   embarked_Unknown  891 non-null    bool
 9   sex_female        891 non-null    bool
 10  sex_male          891 non-null    bool
 11  survived_0        891 non-null    bool
 12  survived_1        891 non-null    bool
 13  who_child         891 non-null    bool
 14  who_man           891 non-null    bool
 15  who_woman         891 non-null    bool
dtypes: bool(16)
memory usage: 14.1 KB

In [52]:
df.dtypes

alone_False         bool
alone_True          bool
class_First         bool
class_Second        bool
class_Third         bool
embarked_C          bool
embarked_Q          bool
embarked_S          bool
embarked_Unknown    bool
sex_female          bool
sex_male            bool
survived_0          bool
survived_1          bool
who_child           bool
who_man             bool
who_woman           bool
dtype: object

In [53]:
df.columns

Index(['alone_False', 'alone_True', 'class_First', 'class_Second',
       'class_Third', 'embarked_C', 'embarked_Q', 'embarked_S',
       'embarked_Unknown', 'sex_female', 'sex_male', 'survived_0',
       'survived_1', 'who_child', 'who_man', 'who_woman'],
      dtype='object')

In [54]:
transactions = []

for i in range(len(df)):
    transactions.append([
        str(df.iloc[i, 0]),
        str(df.iloc[i, 1]),
        str(df.iloc[i, 2]),
        str(df.iloc[i, 3])
    ])

In [43]:
!pip install apyori

/opt/anaconda3/lib/python3.13/pty.py:95: DeprecationWarning: This process (pid=4245) is multi-threaded, use of forkpty() may lead to deadlocks in the child.
  pid, fd = os.forkpty()

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (pyproject.toml) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5996 sha256=daccf5655e2eed1f2131078e1ae47fdd192a34989101f4dd58fee16ada4068c0
  Stored in directory: /Users/pratham0310/Library/Caches/pip/wheels/4d/9f/d0/7ba4ae3f5de2f76ea362170ea0f157e6cc1d1b9aea188175f2
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [55]:
from apyori import apriori 


rules = apriori(
    transactions=transactions,
    min_support=0.1,
    min_confidence=0.5
)

In [56]:
results = list(rules) 
results

[RelationRecord(items=frozenset({'False'}), support=1.0, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'False'}), confidence=1.0, lift=1.0)]),
 RelationRecord(items=frozenset({'True'}), support=1.0, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'True'}), confidence=1.0, lift=1.0)]),
 RelationRecord(items=frozenset({'False', 'True'}), support=1.0, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'False', 'True'}), confidence=1.0, lift=1.0), OrderedStatistic(items_base=frozenset({'False'}), items_add=frozenset({'True'}), confidence=1.0, lift=1.0), OrderedStatistic(items_base=frozenset({'True'}), items_add=frozenset({'False'}), confidence=1.0, lift=1.0)])]

In [61]:
rule_list = []

for result in results:
    for ordered_stat in result.ordered_statistics:
        rule_list.append({
            'Antecedents': ', '.join(ordered_stat.items_base),
            'Consequents': ', '.join(ordered_stat.items_add),
            'Support': result.support,
            'Confidence': ordered_stat.confidence,
        })


results

[RelationRecord(items=frozenset({'False'}), support=1.0, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'False'}), confidence=1.0, lift=1.0)]),
 RelationRecord(items=frozenset({'True'}), support=1.0, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'True'}), confidence=1.0, lift=1.0)]),
 RelationRecord(items=frozenset({'False', 'True'}), support=1.0, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'False', 'True'}), confidence=1.0, lift=1.0), OrderedStatistic(items_base=frozenset({'False'}), items_add=frozenset({'True'}), confidence=1.0, lift=1.0), OrderedStatistic(items_base=frozenset({'True'}), items_add=frozenset({'False'}), confidence=1.0, lift=1.0)])]